python ../adults.py --dirname C:\\Users\\Xavier\\fair_representation\\FairRepresentation\\data\\adults\\results_two_adversary --fairness 0.00 --tag fairness_0.00_0
python ../adults.py --dirname C:\\Users\\Xavier\\fair_representation\\FairRepresentation\\data\\adults\\results_two_adversary --fairness 0.00 --tag fairness_0.00_1
python ../adults.py --dirname C:\\Users\\Xavier\\fair_representation\\FairRepresentation\\data\\adults\\results_two_adversary --fairness 0.00 --tag fairness_0.00_2
python ../adults.py --dirname C:\\Users\\Xavier\\fair_representation\\FairRepresentation\\data\\adults\\results_two_adversary --fairness 0.00 --tag fairness_0.00_3
python ../adults.py --dirname C:\\Users\\Xavier\\fair_representation\\FairRepresentation\\data\\adults\\results_two_adversary --fairness 0.00 --tag fairness_0.00_4
python ../adults.py --dirname C:\\Users\\Xavier\\fair_representation\\FairRepresentation\\data\\adults\\results_two_adversary --fairness 0.00 --tag fairness_0.00_5
python ../adults.py --dirname C:\\Users\\Xavier\\fair_representation\\FairRepresentation\\data\\adults\\results_two_adversary --fairness 0.00 --tag fairness_0.00_6
python ../adults.py --dirname C:\\Users\\Xavier\\fair_representation\\FairRepresentation\\data\\adults\\results_two_adversary --fairness 0.00 --tag fairness_0.00_7
python ../adults.py --dirname C:\\Users\\Xavier\\fair_representation\\FairRepresentation\\data\\adults\\results_two_adversary --fairness 0.00 --tag fairness_0.00_8
python ../adults.py --dirname C:\\Users\\Xavier\\fair_representation\\FairRepresentation\\data\\adults\\results_two_adversary --fairness 0.00 --tag fairness_0.00_9
python ../adults.py --dirname C:\\Users\\Xavier\\fair_representation\\FairRepresentation\\data\\adults\\results_two_adversary --fairness 0.10 --tag fairness_0.10_0
python ../adults.py --dirname C:\\Users\\Xavier\\fair_representation\\FairRepresentation\\data\\adults\\results_two_adversary --fairness 0.10 --tag fairness_0.10_1
python ../adults.py --dirname C:\\Users\\Xavier\\fair_representation\\FairRepresentation\\data\\adults\\results_two_adversary --fairness 0.10 --tag fairness_0.10_2
python ../adults.py --dirname C:\\Users\\Xavier\\fair_representation\\FairRepresentation\\data\\adults\\results_two_adversary --fairness 0.10 --tag fairness_0.10_3
python ../adults.py --dirname C:\\Users\\Xavier\\fair_representation\\FairRepresentation\\data\\adults\\results_two_adversary --fairness 0.10 --tag fairness_0.10_4
python ../adults.py --dirname C:\\Users\\Xavier\\fair_representation\\FairRepresentation\\data\\adults\\results_two_adversary --fairness 0.10 --tag fairness_0.10_5
python ../adults.py --dirname C:\\Users\\Xavier\\fair_representation\\FairRepresentation\\data\\adults\\results_two_adversary --fairness 0.10 --tag fairness_0.10_6
python ../adults.py --dirname C:\\Users\\Xavier\\fair_representation\\FairRepresentation\\data\\adults\\results_two_adversary --fairness 0.10 --tag fairness_0.10_7
python ../adults.py --dirname C:\\Users\\Xavier\\fair_representation\\FairRepresentation\\data\\adults\\results_two_adversary --fairness 0.10 --tag fairness_0.10_8
python ../adults.py --dirname C:\\Users\\Xavier\\fair_representation\\FairRepresentation\\data\\adults\\results_two_adversary --fairness 0.10 --tag fairness_0.10_9
python ../adults.py --dirname C:\\Users\\Xavier\\fair_representation\\FairRepresentation\\data\\adults\\results_two_adversary --fairness 0.20 --tag fairness_0.20_0
python ../adults.py --dirname C:\\Users\\Xavier\\fair_representation\\FairRepresentation\\data\\adults\\results_two_adversary --fairness 0.20 --tag fairness_0.20_1
python ../adults.py --dirname C:\\Users\\Xavier\\fair_representation\\FairRepresentation\\data\\adults\\results_two_adversary --fairness 0.20 --tag fairness_0.20_2
python ../adults.py --dirname C:\\Users\\Xavier\\fair_representation\\FairRepresentation\\data\\adults\\results_two_adversary --fairness 0.20 --tag fairness_0.20_3
python ../adults.py --dirname C:\\Users\\Xavier\\fair_representation\\FairRepresentation\\data\\adults\\results_two_adversary --fairness 0.20 --tag fairness_0.20_4
python ../adults.py --dirname C:\\Users\\Xavier\\fair_representation\\FairRepresentation\\data\\adults\\results_two_adversary --fairness 0.20 --tag fairness_0.20_5
python ../adults.py --dirname C:\\Users\\Xavier\\fair_representation\\FairRepresentation\\data\\adults\\results_two_adversary --fairness 0.20 --tag fairness_0.20_6
python ../adults.py --dirname C:\\Users\\Xavier\\fair_representation\\FairRepresentation\\data\\adults\\results_two_adversary --fairness 0.20 --tag fairness_0.20_7
python ../adults.py --dirname C:\\Users\\Xavier\\fair_representation\\FairRepresentation\\data\\adults\\results_two_adversary --fairness 0.20 --tag fairness_0.20_8
python ../adults.py --dirname C:\\Users\\Xavier\\fair_representation\\FairRepresentation\\data\\adults\\results_two_adversary --fairness 0.20 --tag fairness_0.20_9
python ../adults.py --dirname C:\\Users\\Xavier\\fair_representation\\FairRepresentation\\data\\adults\\results_two_adversary --fairness 0.30 --tag fairness_0.30_0
python ../adults.py --dirname C:\\Users\\Xavier\\fair_representation\\FairRepresentation\\data\\adults\\results_two_adversary --fairness 0.30 --tag fairness_0.30_1
python ../adults.py --dirname C:\\Users\\Xavier\\fair_representation\\FairRepresentation\\data\\adults\\results_two_adversary --fairness 0.30 --tag fairness_0.30_2
python ../adults.py --dirname C:\\Users\\Xavier\\fair_representation\\FairRepresentation\\data\\adults\\results_two_adversary --fairness 0.30 --tag fairness_0.30_3
python ../adults.py --dirname C:\\Users\\Xavier\\fair_representation\\FairRepresentation\\data\\adults\\results_two_adversary --fairness 0.30 --tag fairness_0.30_4
python ../adults.py --dirname C:\\Users\\Xavier\\fair_representation\\FairRepresentation\\data\\adults\\results_two_adversary --fairness 0.30 --tag fairness_0.30_5
python ../adults.py --dirname C:\\Users\\Xavier\\fair_representation\\FairRepresentation\\data\\adults\\results_two_adversary --fairness 0.30 --tag fairness_0.30_6
python ../adults.py --dirname C:\\Users\\Xavier\\fair_representation\\FairRepresentation\\data\\adults\\results_two_adversary --fairness 0.30 --tag fairness_0.30_7
python ../adults.py --dirname C:\\Users\\Xavier\\fair_representation\\FairRepresentation\\data\\adults\\results_two_adversary --fairness 0.30 --tag fairness_0.30_8
python ../adults.py --dirname C:\\Users\\Xavier\\fair_representation\\FairRepresentation\\data\\adults\\results_two_adversary --fairness 0.30 --tag fairness_0.30_9
python ../adults.py --dirname C:\\Users\\Xavier\\fair_representation\\FairRepresentation\\data\\adults\\results_two_adversary --fairness 0.40 --tag fairness_0.40_0
python ../adults.py --dirname C:\\Users\\Xavier\\fair_representation\\FairRepresentation\\data\\adults\\results_two_adversary --fairness 0.40 --tag fairness_0.40_1
python ../adults.py --dirname C:\\Users\\Xavier\\fair_representation\\FairRepresentation\\data\\adults\\results_two_adversary --fairness 0.40 --tag fairness_0.40_2
python ../adults.py --dirname C:\\Users\\Xavier\\fair_representation\\FairRepresentation\\data\\adults\\results_two_adversary --fairness 0.40 --tag fairness_0.40_3
python ../adults.py --dirname C:\\Users\\Xavier\\fair_representation\\FairRepresentation\\data\\adults\\results_two_adversary --fairness 0.40 --tag fairness_0.40_4
python ../adults.py --dirname C:\\Users\\Xavier\\fair_representation\\FairRepresentation\\data\\adults\\results_two_adversary --fairness 0.40 --tag fairness_0.40_5
python ../adults.py --dirname C:\\Users\\Xavier\\fair_representation\\FairRepresentation\\data\\adults\\results_two_adversary --fairness 0.40 --tag fairness_0.40_6
python ../adults.py --dirname C:\\Users\\Xavier\\fair_representation\\FairRepresentation\\data\\adults\\results_two_adversary --fairness 0.40 --tag fairness_0.40_7
python ../adults.py --dirname C:\\Users\\Xavier\\fair_representation\\FairRepresentation\\data\\adults\\results_two_adversary --fairness 0.40 --tag fairness_0.40_8
python ../adults.py --dirname C:\\Users\\Xavier\\fair_representation\\FairRepresentation\\data\\adults\\results_two_adversary --fairness 0.40 --tag fairness_0.40_9
python ../adults.py --dirname C:\\Users\\Xavier\\fair_representation\\FairRepresentation\\data\\adults\\results_two_adversary --fairness 0.50 --tag fairness_0.50_0
python ../adults.py --dirname C:\\Users\\Xavier\\fair_representation\\FairRepresentation\\data\\adults\\results_two_adversary --fairness 0.50 --tag fairness_0.50_1
python ../adults.py --dirname C:\\Users\\Xavier\\fair_representation\\FairRepresentation\\data\\adults\\results_two_adversary --fairness 0.50 --tag fairness_0.50_2
python ../adults.py --dirname C:\\Users\\Xavier\\fair_representation\\FairRepresentation\\data\\adults\\results_two_adversary --fairness 0.50 --tag fairness_0.50_3
python ../adults.py --dirname C:\\Users\\Xavier\\fair_representation\\FairRepresentation\\data\\adults\\results_two_adversary --fairness 0.50 --tag fairness_0.50_4
python ../adults.py --dirname C:\\Users\\Xavier\\fair_representation\\FairRepresentation\\data\\adults\\results_two_adversary --fairness 0.50 --tag fairness_0.50_5
python ../adults.py --dirname C:\\Users\\Xavier\\fair_representation\\FairRepresentation\\data\\adults\\results_two_adversary --fairness 0.50 --tag fairness_0.50_6
python ../adults.py --dirname C:\\Users\\Xavier\\fair_representation\\FairRepresentation\\data\\adults\\results_two_adversary --fairness 0.50 --tag fairness_0.50_7
python ../adults.py --dirname C:\\Users\\Xavier\\fair_representation\\FairRepresentation\\data\\adults\\results_two_adversary --fairness 0.50 --tag fairness_0.50_8
python ../adults.py --dirname C:\\Users\\Xavier\\fair_representation\\FairRepresentation\\data\\adults\\results_two_adversary --fairness 0.50 --tag fairness_0.50_9
python ../adults.py --dirname C:\\Users\\Xavier\\fair_representation\\FairRepresentation\\data\\adults\\results_two_adversary --fairness 0.60 --tag fairness_0.60_0
python ../adults.py --dirname C:\\Users\\Xavier\\fair_representation\\FairRepresentation\\data\\adults\\results_two_adversary --fairness 0.60 --tag fairness_0.60_1
python ../adults.py --dirname C:\\Users\\Xavier\\fair_representation\\FairRepresentation\\data\\adults\\results_two_adversary --fairness 0.60 --tag fairness_0.60_2
python ../adults.py --dirname C:\\Users\\Xavier\\fair_representation\\FairRepresentation\\data\\adults\\results_two_adversary --fairness 0.60 --tag fairness_0.60_3
python ../adults.py --dirname C:\\Users\\Xavier\\fair_representation\\FairRepresentation\\data\\adults\\results_two_adversary --fairness 0.60 --tag fairness_0.60_4
python ../adults.py --dirname C:\\Users\\Xavier\\fair_representation\\FairRepresentation\\data\\adults\\results_two_adversary --fairness 0.60 --tag fairness_0.60_5
python ../adults.py --dirname C:\\Users\\Xavier\\fair_representation\\FairRepresentation\\data\\adults\\results_two_adversary --fairness 0.60 --tag fairness_0.60_6
python ../adults.py --dirname C:\\Users\\Xavier\\fair_representation\\FairRepresentation\\data\\adults\\results_two_adversary --fairness 0.60 --tag fairness_0.60_7
python ../adults.py --dirname C:\\Users\\Xavier\\fair_representation\\FairRepresentation\\data\\adults\\results_two_adversary --fairness 0.60 --tag fairness_0.60_8
python ../adults.py --dirname C:\\Users\\Xavier\\fair_representation\\FairRepresentation\\data\\adults\\results_two_adversary --fairness 0.60 --tag fairness_0.60_9
python ../adults.py --dirname C:\\Users\\Xavier\\fair_representation\\FairRepresentation\\data\\adults\\results_two_adversary --fairness 0.70 --tag fairness_0.70_0
python ../adults.py --dirname C:\\Users\\Xavier\\fair_representation\\FairRepresentation\\data\\adults\\results_two_adversary --fairness 0.70 --tag fairness_0.70_1
python ../adults.py --dirname C:\\Users\\Xavier\\fair_representation\\FairRepresentation\\data\\adults\\results_two_adversary --fairness 0.70 --tag fairness_0.70_2
python ../adults.py --dirname C:\\Users\\Xavier\\fair_representation\\FairRepresentation\\data\\adults\\results_two_adversary --fairness 0.70 --tag fairness_0.70_3
python ../adults.py --dirname C:\\Users\\Xavier\\fair_representation\\FairRepresentation\\data\\adults\\results_two_adversary --fairness 0.70 --tag fairness_0.70_4
python ../adults.py --dirname C:\\Users\\Xavier\\fair_representation\\FairRepresentation\\data\\adults\\results_two_adversary --fairness 0.70 --tag fairness_0.70_5
python ../adults.py --dirname C:\\Users\\Xavier\\fair_representation\\FairRepresentation\\data\\adults\\results_two_adversary --fairness 0.70 --tag fairness_0.70_6
python ../adults.py --dirname C:\\Users\\Xavier\\fair_representation\\FairRepresentation\\data\\adults\\results_two_adversary --fairness 0.70 --tag fairness_0.70_7
python ../adults.py --dirname C:\\Users\\Xavier\\fair_representation\\FairRepresentation\\data\\adults\\results_two_adversary --fairness 0.70 --tag fairness_0.70_8
python ../adults.py --dirname C:\\Users\\Xavier\\fair_representation\\FairRepresentation\\data\\adults\\results_two_adversary --fairness 0.70 --tag fairness_0.70_9
python ../adults.py --dirname C:\\Users\\Xavier\\fair_representation\\FairRepresentation\\data\\adults\\results_two_adversary --fairness 0.80 --tag fairness_0.80_0
python ../adults.py --dirname C:\\Users\\Xavier\\fair_representation\\FairRepresentation\\data\\adults\\results_two_adversary --fairness 0.80 --tag fairness_0.80_1
python ../adults.py --dirname C:\\Users\\Xavier\\fair_representation\\FairRepresentation\\data\\adults\\results_two_adversary --fairness 0.80 --tag fairness_0.80_2
python ../adults.py --dirname C:\\Users\\Xavier\\fair_representation\\FairRepresentation\\data\\adults\\results_two_adversary --fairness 0.80 --tag fairness_0.80_3
python ../adults.py --dirname C:\\Users\\Xavier\\fair_representation\\FairRepresentation\\data\\adults\\results_two_adversary --fairness 0.80 --tag fairness_0.80_4
python ../adults.py --dirname C:\\Users\\Xavier\\fair_representation\\FairRepresentation\\data\\adults\\results_two_adversary --fairness 0.80 --tag fairness_0.80_5
python ../adults.py --dirname C:\\Users\\Xavier\\fair_representation\\FairRepresentation\\data\\adults\\results_two_adversary --fairness 0.80 --tag fairness_0.80_6
python ../adults.py --dirname C:\\Users\\Xavier\\fair_representation\\FairRepresentation\\data\\adults\\results_two_adversary --fairness 0.80 --tag fairness_0.80_7
python ../adults.py --dirname C:\\Users\\Xavier\\fair_representation\\FairRepresentation\\data\\adults\\results_two_adversary --fairness 0.80 --tag fairness_0.80_8
python ../adults.py --dirname C:\\Users\\Xavier\\fair_representation\\FairRepresentation\\data\\adults\\results_two_adversary --fairness 0.80 --tag fairness_0.80_9
python ../adults.py --dirname C:\\Users\\Xavier\\fair_representation\\FairRepresentation\\data\\adults\\results_two_adversary --fairness 0.90 --tag fairness_0.90_0
python ../adults.py --dirname C:\\Users\\Xavier\\fair_representation\\FairRepresentation\\data\\adults\\results_two_adversary --fairness 0.90 --tag fairness_0.90_1
python ../adults.py --dirname C:\\Users\\Xavier\\fair_representation\\FairRepresentation\\data\\adults\\results_two_adversary --fairness 0.90 --tag fairness_0.90_2
python ../adults.py --dirname C:\\Users\\Xavier\\fair_representation\\FairRepresentation\\data\\adults\\results_two_adversary --fairness 0.90 --tag fairness_0.90_3
python ../adults.py --dirname C:\\Users\\Xavier\\fair_representation\\FairRepresentation\\data\\adults\\results_two_adversary --fairness 0.90 --tag fairness_0.90_4
python ../adults.py --dirname C:\\Users\\Xavier\\fair_representation\\FairRepresentation\\data\\adults\\results_two_adversary --fairness 0.90 --tag fairness_0.90_5
python ../adults.py --dirname C:\\Users\\Xavier\\fair_representation\\FairRepresentation\\data\\adults\\results_two_adversary --fairness 0.90 --tag fairness_0.90_6
python ../adults.py --dirname C:\\Users\\Xavier\\fair_representation\\FairRepresentation\\data\\adults\\results_two_adversary --fairness 0.90 --tag fairness_0.90_7
python ../adults.py --dirname C:\\Users\\Xavier\\fair_representation\\FairRepresentation\\data\\adults\\results_two_adversary --fairness 0.90 --tag fairness_0.90_8
python ../adults.py --dirname C:\\Users\\Xavier\\fair_representation\\FairRepresentation\\data\\adults\\results_two_adversary --fairness 0.90 --tag fairness_0.90_9
python ../adults.py --dirname C:\\Users\\Xavier\\fair_representation\\FairRepresentation\\data\\adults\\results_two_adversary --fairness 1.00 --tag fairness_1.00_0
python ../adults.py --dirname C:\\Users\\Xavier\\fair_representation\\FairRepresentation\\data\\adults\\results_two_adversary --fairness 1.00 --tag fairness_1.00_1
python ../adults.py --dirname C:\\Users\\Xavier\\fair_representation\\FairRepresentation\\data\\adults\\results_two_adversary --fairness 1.00 --tag fairness_1.00_2
python ../adults.py --dirname C:\\Users\\Xavier\\fair_representation\\FairRepresentation\\data\\adults\\results_two_adversary --fairness 1.00 --tag fairness_1.00_3
python ../adults.py --dirname C:\\Users\\Xavier\\fair_representation\\FairRepresentation\\data\\adults\\results_two_adversary --fairness 1.00 --tag fairness_1.00_4
python ../adults.py --dirname C:\\Users\\Xavier\\fair_representation\\FairRepresentation\\data\\adults\\results_two_adversary --fairness 1.00 --tag fairness_1.00_5
python ../adults.py --dirname C:\\Users\\Xavier\\fair_representation\\FairRepresentation\\data\\adults\\results_two_adversary --fairness 1.00 --tag fairness_1.00_6
python ../adults.py --dirname C:\\Users\\Xavier\\fair_representation\\FairRepresentation\\data\\adults\\results_two_adversary --fairness 1.00 --tag fairness_1.00_7
python ../adults.py --dirname C:\\Users\\Xavier\\fair_representation\\FairRepresentation\\data\\adults\\results_two_adversary --fairness 1.00 --tag fairness_1.00_8
python ../adults.py --dirname C:\\Users\\Xavier\\fair_representation\\FairRepresentation\\data\\adults\\results_two_adversary --fairness 1.00 --tag fairness_1.00_9
python ../adults.py --dirname C:\\Users\\Xavier\\fair_representation\\FairRepresentation\\data\\adults\\results_two_adversary --fairness 1.10 --tag fairness_1.10_0
python ../adults.py --dirname C:\\Users\\Xavier\\fair_representation\\FairRepresentation\\data\\adults\\results_two_adversary --fairness 1.10 --tag fairness_1.10_1
python ../adults.py --dirname C:\\Users\\Xavier\\fair_representation\\FairRepresentation\\data\\adults\\results_two_adversary --fairness 1.10 --tag fairness_1.10_2
python ../adults.py --dirname C:\\Users\\Xavier\\fair_representation\\FairRepresentation\\data\\adults\\results_two_adversary --fairness 1.10 --tag fairness_1.10_3
python ../adults.py --dirname C:\\Users\\Xavier\\fair_representation\\FairRepresentation\\data\\adults\\results_two_adversary --fairness 1.10 --tag fairness_1.10_4
python ../adults.py --dirname C:\\Users\\Xavier\\fair_representation\\FairRepresentation\\data\\adults\\results_two_adversary --fairness 1.10 --tag fairness_1.10_5
python ../adults.py --dirname C:\\Users\\Xavier\\fair_representation\\FairRepresentation\\data\\adults\\results_two_adversary --fairness 1.10 --tag fairness_1.10_6
python ../adults.py --dirname C:\\Users\\Xavier\\fair_representation\\FairRepresentation\\data\\adults\\results_two_adversary --fairness 1.10 --tag fairness_1.10_7
python ../adults.py --dirname C:\\Users\\Xavier\\fair_representation\\FairRepresentation\\data\\adults\\results_two_adversary --fairness 1.10 --tag fairness_1.10_8
python ../adults.py --dirname C:\\Users\\Xavier\\fair_representation\\FairRepresentation\\data\\adults\\results_two_adversary --fairness 1.10 --tag fairness_1.10_9
python ../adults.py --dirname C:\\Users\\Xavier\\fair_representation\\FairRepresentation\\data\\adults\\results_two_adversary --fairness 1.20 --tag fairness_1.20_0
python ../adults.py --dirname C:\\Users\\Xavier\\fair_representation\\FairRepresentation\\data\\adults\\results_two_adversary --fairness 1.20 --tag fairness_1.20_1
python ../adults.py --dirname C:\\Users\\Xavier\\fair_representation\\FairRepresentation\\data\\adults\\results_two_adversary --fairness 1.20 --tag fairness_1.20_2
python ../adults.py --dirname C:\\Users\\Xavier\\fair_representation\\FairRepresentation\\data\\adults\\results_two_adversary --fairness 1.20 --tag fairness_1.20_3
python ../adults.py --dirname C:\\Users\\Xavier\\fair_representation\\FairRepresentation\\data\\adults\\results_two_adversary --fairness 1.20 --tag fairness_1.20_4
python ../adults.py --dirname C:\\Users\\Xavier\\fair_representation\\FairRepresentation\\data\\adults\\results_two_adversary --fairness 1.20 --tag fairness_1.20_5
python ../adults.py --dirname C:\\Users\\Xavier\\fair_representation\\FairRepresentation\\data\\adults\\results_two_adversary --fairness 1.20 --tag fairness_1.20_6
python ../adults.py --dirname C:\\Users\\Xavier\\fair_representation\\FairRepresentation\\data\\adults\\results_two_adversary --fairness 1.20 --tag fairness_1.20_7
python ../adults.py --dirname C:\\Users\\Xavier\\fair_representation\\FairRepresentation\\data\\adults\\results_two_adversary --fairness 1.20 --tag fairness_1.20_8
python ../adults.py --dirname C:\\Users\\Xavier\\fair_representation\\FairRepresentation\\data\\adults\\results_two_adversary --fairness 1.20 --tag fairness_1.20_9
python ../adults.py --dirname C:\\Users\\Xavier\\fair_representation\\FairRepresentation\\data\\adults\\results_two_adversary --fairness 1.30 --tag fairness_1.30_0
python ../adults.py --dirname C:\\Users\\Xavier\\fair_representation\\FairRepresentation\\data\\adults\\results_two_adversary --fairness 1.30 --tag fairness_1.30_1
python ../adults.py --dirname C:\\Users\\Xavier\\fair_representation\\FairRepresentation\\data\\adults\\results_two_adversary --fairness 1.30 --tag fairness_1.30_2
python ../adults.py --dirname C:\\Users\\Xavier\\fair_representation\\FairRepresentation\\data\\adults\\results_two_adversary --fairness 1.30 --tag fairness_1.30_3
python ../adults.py --dirname C:\\Users\\Xavier\\fair_representation\\FairRepresentation\\data\\adults\\results_two_adversary --fairness 1.30 --tag fairness_1.30_4
python ../adults.py --dirname C:\\Users\\Xavier\\fair_representation\\FairRepresentation\\data\\adults\\results_two_adversary --fairness 1.30 --tag fairness_1.30_5
python ../adults.py --dirname C:\\Users\\Xavier\\fair_representation\\FairRepresentation\\data\\adults\\results_two_adversary --fairness 1.30 --tag fairness_1.30_6
python ../adults.py --dirname C:\\Users\\Xavier\\fair_representation\\FairRepresentation\\data\\adults\\results_two_adversary --fairness 1.30 --tag fairness_1.30_7
python ../adults.py --dirname C:\\Users\\Xavier\\fair_representation\\FairRepresentation\\data\\adults\\results_two_adversary --fairness 1.30 --tag fairness_1.30_8
python ../adults.py --dirname C:\\Users\\Xavier\\fair_representation\\FairRepresentation\\data\\adults\\results_two_adversary --fairness 1.30 --tag fairness_1.30_9
python ../adults.py --dirname C:\\Users\\Xavier\\fair_representation\\FairRepresentation\\data\\adults\\results_two_adversary --fairness 1.40 --tag fairness_1.40_0
python ../adults.py --dirname C:\\Users\\Xavier\\fair_representation\\FairRepresentation\\data\\adults\\results_two_adversary --fairness 1.40 --tag fairness_1.40_1
python ../adults.py --dirname C:\\Users\\Xavier\\fair_representation\\FairRepresentation\\data\\adults\\results_two_adversary --fairness 1.40 --tag fairness_1.40_2
python ../adults.py --dirname C:\\Users\\Xavier\\fair_representation\\FairRepresentation\\data\\adults\\results_two_adversary --fairness 1.40 --tag fairness_1.40_3
python ../adults.py --dirname C:\\Users\\Xavier\\fair_representation\\FairRepresentation\\data\\adults\\results_two_adversary --fairness 1.40 --tag fairness_1.40_4
python ../adults.py --dirname C:\\Users\\Xavier\\fair_representation\\FairRepresentation\\data\\adults\\results_two_adversary --fairness 1.40 --tag fairness_1.40_5
python ../adults.py --dirname C:\\Users\\Xavier\\fair_representation\\FairRepresentation\\data\\adults\\results_two_adversary --fairness 1.40 --tag fairness_1.40_6
python ../adults.py --dirname C:\\Users\\Xavier\\fair_representation\\FairRepresentation\\data\\adults\\results_two_adversary --fairness 1.40 --tag fairness_1.40_7
python ../adults.py --dirname C:\\Users\\Xavier\\fair_representation\\FairRepresentation\\data\\adults\\results_two_adversary --fairness 1.40 --tag fairness_1.40_8
python ../adults.py --dirname C:\\Users\\Xavier\\fair_representation\\FairRepresentation\\data\\adults\\results_two_adversary --fairness 1.40 --tag fairness_1.40_9
python ..\\..\\lafr\\results.py --dirname C:\\Users\\Xavier\\fair_representation\\FairRepresentation\\data\\adults\\results_two_adversary --config adult_config.yml
