python ../test_latfr.py --unbalance 0.0 --tag unbalance_0.0_0
python ../test_latfr.py --unbalance 0.0 --tag unbalance_0.0_1
python ../test_latfr.py --unbalance 0.0 --tag unbalance_0.0_2
python ../test_latfr.py --unbalance 0.0 --tag unbalance_0.0_3
python ../test_latfr.py --unbalance 0.0 --tag unbalance_0.0_4
python ../test_latfr.py --unbalance 0.0 --tag unbalance_0.0_5
python ../test_latfr.py --unbalance 0.0 --tag unbalance_0.0_6
python ../test_latfr.py --unbalance 0.0 --tag unbalance_0.0_7
python ../test_latfr.py --unbalance 0.0 --tag unbalance_0.0_8
python ../test_latfr.py --unbalance 0.0 --tag unbalance_0.0_9
python ../test_latfr.py --unbalance 0.25 --tag unbalance_0.25_0
python ../test_latfr.py --unbalance 0.25 --tag unbalance_0.25_1
python ../test_latfr.py --unbalance 0.25 --tag unbalance_0.25_2
python ../test_latfr.py --unbalance 0.25 --tag unbalance_0.25_3
python ../test_latfr.py --unbalance 0.25 --tag unbalance_0.25_4
python ../test_latfr.py --unbalance 0.25 --tag unbalance_0.25_5
python ../test_latfr.py --unbalance 0.25 --tag unbalance_0.25_6
python ../test_latfr.py --unbalance 0.25 --tag unbalance_0.25_7
python ../test_latfr.py --unbalance 0.25 --tag unbalance_0.25_8
python ../test_latfr.py --unbalance 0.25 --tag unbalance_0.25_9
python ../test_latfr.py --unbalance 0.5 --tag unbalance_0.5_0
python ../test_latfr.py --unbalance 0.5 --tag unbalance_0.5_1
python ../test_latfr.py --unbalance 0.5 --tag unbalance_0.5_2
python ../test_latfr.py --unbalance 0.5 --tag unbalance_0.5_3
python ../test_latfr.py --unbalance 0.5 --tag unbalance_0.5_4
python ../test_latfr.py --unbalance 0.5 --tag unbalance_0.5_5
python ../test_latfr.py --unbalance 0.5 --tag unbalance_0.5_6
python ../test_latfr.py --unbalance 0.5 --tag unbalance_0.5_7
python ../test_latfr.py --unbalance 0.5 --tag unbalance_0.5_8
python ../test_latfr.py --unbalance 0.5 --tag unbalance_0.5_9
python ../test_latfr.py --unbalance 0.75 --tag unbalance_0.75_0
python ../test_latfr.py --unbalance 0.75 --tag unbalance_0.75_1
python ../test_latfr.py --unbalance 0.75 --tag unbalance_0.75_2
python ../test_latfr.py --unbalance 0.75 --tag unbalance_0.75_3
python ../test_latfr.py --unbalance 0.75 --tag unbalance_0.75_4
python ../test_latfr.py --unbalance 0.75 --tag unbalance_0.75_5
python ../test_latfr.py --unbalance 0.75 --tag unbalance_0.75_6
python ../test_latfr.py --unbalance 0.75 --tag unbalance_0.75_7
python ../test_latfr.py --unbalance 0.75 --tag unbalance_0.75_8
python ../test_latfr.py --unbalance 0.75 --tag unbalance_0.75_9
python ../test_latfr.py --unbalance 1.0 --tag unbalance_1.0_0
python ../test_latfr.py --unbalance 1.0 --tag unbalance_1.0_1
python ../test_latfr.py --unbalance 1.0 --tag unbalance_1.0_2
python ../test_latfr.py --unbalance 1.0 --tag unbalance_1.0_3
python ../test_latfr.py --unbalance 1.0 --tag unbalance_1.0_4
python ../test_latfr.py --unbalance 1.0 --tag unbalance_1.0_5
python ../test_latfr.py --unbalance 1.0 --tag unbalance_1.0_6
python ../test_latfr.py --unbalance 1.0 --tag unbalance_1.0_7
python ../test_latfr.py --unbalance 1.0 --tag unbalance_1.0_8
python ../test_latfr.py --unbalance 1.0 --tag unbalance_1.0_9
python ../test_latfr.py --unbalance 1.25 --tag unbalance_1.25_0
python ../test_latfr.py --unbalance 1.25 --tag unbalance_1.25_1
python ../test_latfr.py --unbalance 1.25 --tag unbalance_1.25_2
python ../test_latfr.py --unbalance 1.25 --tag unbalance_1.25_3
python ../test_latfr.py --unbalance 1.25 --tag unbalance_1.25_4
python ../test_latfr.py --unbalance 1.25 --tag unbalance_1.25_5
python ../test_latfr.py --unbalance 1.25 --tag unbalance_1.25_6
python ../test_latfr.py --unbalance 1.25 --tag unbalance_1.25_7
python ../test_latfr.py --unbalance 1.25 --tag unbalance_1.25_8
python ../test_latfr.py --unbalance 1.25 --tag unbalance_1.25_9
python ../test_latfr.py --unbalance 1.5 --tag unbalance_1.5_0
python ../test_latfr.py --unbalance 1.5 --tag unbalance_1.5_1
python ../test_latfr.py --unbalance 1.5 --tag unbalance_1.5_2
python ../test_latfr.py --unbalance 1.5 --tag unbalance_1.5_3
python ../test_latfr.py --unbalance 1.5 --tag unbalance_1.5_4
python ../test_latfr.py --unbalance 1.5 --tag unbalance_1.5_5
python ../test_latfr.py --unbalance 1.5 --tag unbalance_1.5_6
python ../test_latfr.py --unbalance 1.5 --tag unbalance_1.5_7
python ../test_latfr.py --unbalance 1.5 --tag unbalance_1.5_8
python ../test_latfr.py --unbalance 1.5 --tag unbalance_1.5_9
python ../test_latfr.py --unbalance 1.75 --tag unbalance_1.75_0
python ../test_latfr.py --unbalance 1.75 --tag unbalance_1.75_1
python ../test_latfr.py --unbalance 1.75 --tag unbalance_1.75_2
python ../test_latfr.py --unbalance 1.75 --tag unbalance_1.75_3
python ../test_latfr.py --unbalance 1.75 --tag unbalance_1.75_4
python ../test_latfr.py --unbalance 1.75 --tag unbalance_1.75_5
python ../test_latfr.py --unbalance 1.75 --tag unbalance_1.75_6
python ../test_latfr.py --unbalance 1.75 --tag unbalance_1.75_7
python ../test_latfr.py --unbalance 1.75 --tag unbalance_1.75_8
python ../test_latfr.py --unbalance 1.75 --tag unbalance_1.75_9
python ../test_latfr.py --unbalance 2.0 --tag unbalance_2.0_0
python ../test_latfr.py --unbalance 2.0 --tag unbalance_2.0_1
python ../test_latfr.py --unbalance 2.0 --tag unbalance_2.0_2
python ../test_latfr.py --unbalance 2.0 --tag unbalance_2.0_3
python ../test_latfr.py --unbalance 2.0 --tag unbalance_2.0_4
python ../test_latfr.py --unbalance 2.0 --tag unbalance_2.0_5
python ../test_latfr.py --unbalance 2.0 --tag unbalance_2.0_6
python ../test_latfr.py --unbalance 2.0 --tag unbalance_2.0_7
python ../test_latfr.py --unbalance 2.0 --tag unbalance_2.0_8
python ../test_latfr.py --unbalance 2.0 --tag unbalance_2.0_9
